package sys.modelo;
// Generated 17/09/2023 22:53:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private Integer idLibro;
     private String titulo;
     private String autor;
     private String genero;
     private BigDecimal precio;
     private String codigo;

    public Libro() {
    }

    public Libro(String titulo, String autor, String genero, BigDecimal precio, String codigo) {
       this.titulo = titulo;
       this.autor = autor;
       this.genero = genero;
       this.precio = precio;
       this.codigo = codigo;
    }
   
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }




}


